test_dbt:
  outputs:
    dev:
      type: postgres
      threads: 5
      host: localhost
      port: 5432
      user: postgres
      pass: Datorama01
      dbname: test_dbt
      schema: public

  target: dev
